### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by wezm** [sminez/penrose#1]
Really like the look of this. I’m currently an Awesome user but could see myself switching to Penrose in the future. I have a dual screen set up so multi-monitor support is one thing preventing me switching. You mentioned that multi-monitor support isn’t working yet in the video but I figured it would be worth having an issue to track it.

**Comment by sminez** [comment]
Thanks for taking the time to raise it as an issue 👍 hopefully I'm not too far off (famous last words...)

**Comment by sminez** [comment]
@wezm I've got an initial take on multi-monitor now working on https://github.com/sminez/penrose/tree/issue-1/multi-monitor . There is some tidying up to do and some improvements to be made for the methods exposed for keybindings. If you can, could you take a look and let me know what you think?

**Comment by sminez** [comment]
The merge of #10 adds initial multi-monitor support. I'm not sure yet how this will interact with things like status bars so if anyone is able to try it out and provide feedback that would be really helpful.

**Comment by wezm** [comment]
Cool, I'll try it out but might not have time until the weekend.

**Comment by wezm** [comment]
I gave it a very quick test. It seems to work. Windows were managed across both screens. I was able to run an `xrandr` command to adjust the layout and that worked fine. At some point I'll need to invest more time building a full config and work out what to do about a status bar. I currently use Awesome, which has one built in.

![Screenshot from 2020-08-02 14-55-13](https://user-images.githubusercontent.com/21787/89115882-c1ec5b00-d4d0-11ea-8084-9580a6ab26e3.png)

**Comment by sminez** [comment]
Hi @wezm, glad that Penrose is working for your multi monitor setup! A built in status bar is next on my list actually, I was previously using dwm and currently have polybar set up as a stop gap which is what you'll see in the screenshots.
I wasn't planning on anything too fancy initially but the bar will be interfacing with Penrose using a trait in a similar style to XConn so that if you want to add your own impl it should be relatively straightforward (hopefully!)
