### ISSUE TITLE
xmonad-like automations

### ISSUE THREAD

**Issue by as3ii** [sminez/penrose#105]
### Is your feature request related to a problem? Please describe

There are many steps that a normal user would not want to do, such as:
- initialize Cargo.toml with the basic dependency needed
- have the display manager find the compiled window manager

### Describe the change / addition you'd like to see made

Implement a little program/script similar to `xmonad` that will automatically manage the _configuration_, saving the user from filling the `Cargo.toml` with the base dependencies, initialize `main.rs` with a really basic configuration, and put the compiled files in the right place to be found by the display manager (or automatically configure the display manager to find the binary)

### Describe alternatives you've considered

Leave everything as it is. The user will write their own script to manage everything, if they wants

**Comment by sminez** [comment]
I've deliberately not done something like this because (as stated in the README) Penrose is library, not a window manager binary that you install and configure.

The end user can (and should) be in control of how they use Penrose as a crate: wrapping the crate creation, compile and install in a script is a partial automation step that confuses the mental model.

This is an issue I have with xmond's approach: xmonad _is_ a library, and you are compiling a binary using it. You need to deal with compile errors and managing dependencies. Having the helper program hide that away and presenting failures as "errors in config" is not helpful in my opinion.

That said, if you would like to write such a script and support / maintain it, I'd be happy to include a link to it in the README as an alternative to the recommended use of Penrose: as a library. But it's not going part of the Rust crate itself I'm afraid.

If users don't want to maintain their own software, they should not be using Penrose for their window manager :wink: there are many, many alternatives that would be a far better choice.
