### ISSUE TITLE
Colours: using u32 or draw::Color

### ISSUE THREAD

**Issue by lewis-weinberger** [sminez/penrose#108]
Hi, really cool project - thanks for sharing it!

I think the documentation/implementation is incorrect for the [`new_from_hex`](https://github.com/sminez/penrose/blob/develop/src/draw/mod.rs#L89-L99) impl of the `draw::Color` type:

```rust
/// Create a new Color from a hex encoded u32: 0xRRGGBB or 0xRRGGBBAA
pub fn new_from_hex(hex: u32) -> Self {
    let floats: Vec<f64> = hex
        .to_be_bytes()
        .iter()
        .map(|n| *n as f64 / 255.0)
        .collect();

    let (r, g, b, a) = (floats[0], floats[1], floats[2], floats[3]);
    Self { r, g, b, a }
}
```

This function works for `0xRRGGBBAA` but *not* for `0xRRGGBB` (perhaps easier to see as `0x00RRGGBB`). This difference is handled correctly in [`TryFrom<&str>`](https://github.com/sminez/penrose/blob/develop/src/draw/mod.rs#L152-L166) which takes into account the number of bytes in the encoding.

I came across this whilst setting some default colours as constants:

```rust
// 0xRRGGBB encoding
const FOCUS: u32 = 0x55AAAA;
const NORMAL: u32 = 0x9EEEEE;
```

- The `focused_border` and `unfocused_border` impls of `core::config::ConfigBuilder` take `u32` colours as arguments (and seem to expect `0xRRGGBB`). 
- However to use these same constants to create, e.g. a `draw::TextStyle`,  requires `draw::Color` values rather than `u32`, and these will currently result in different colours (since `From<u32>` uses the above `new_from_hex`).

**Comment by sminez** [comment]
Ah! Sorry that is one I've never hit because I always use the default border colors :facepalm: 

I think that the best thing is probably to have `Config` use `Color` as well but that'll involve some extra tinkering to make sure that everything lines up. I think most likely, you'll end up defining them as `&str` literals and both the status bar and config will accept anything that can be turned _into_ a color.

I _think_ it should be possible to do this without breaking to much, but anyone relying on getting a `u32` out of `config.focused_border` or `config.unfocused_border` will have to do a little bit of refactoring I suspect.

**Comment by lewis-weinberger** [comment]
> I think most likely, you'll end up defining them as &str literals and both the status bar and config will accept anything that can be turned into a color.

Yes that sounds like a good approach!

**Comment by sminez** [comment]
@lewis-weinberger #123 should fix the issue you were having (the new setter methods return errors as they need to accomodate `TryFrom` not just `From` but the updated examples in the docs should show you what needs changing :+1:
