### ISSUE TITLE
Bug in setting screen from cursor position

### ISSUE THREAD

**Issue by Niedzwiedzw** [sminez/penrose#134]
I haven't experienced it, but reading through the code base with my friend @krskibin wenoticed height is added to the x variable, shouldn't it be added the the y one? (y2 = y1 + h) rather than (y2 = x1 + h)
![image](https://user-images.githubusercontent.com/22037927/107157532-d54b1800-6984-11eb-8812-37afe9d49e90.png)
Also may I suggest writing some unit tests for math related stuff? cheers

**Comment by sminez** [comment]
Urgh, wow that's gross :facepalm: 

That's been there since nearly the start of `penrose` I think...There are new helper functions with tests in `core/data_types` that can be unsed instead of this. I think this is only used when setting the screen from cursor position which mostly works fine despite this bug somehow... I'll get it swapped over to the new logic :+1:
