### ISSUE TITLE
Steam doesn't start on current develop branch

### ISSUE THREAD

**Issue by Niedzwiedzw** [sminez/penrose#135]
### Describe the bug
when running steam either from dmenu or from the terminal it doesn't show. Maybe it's due to tray not being supported.

### To Reproduce

1. open terminal
2. type `steam`
### Expected behavior

I should see steam windows running

### Versions & OS Details
niedzwiedz@niedzwiedz-pc
------------------------
OS: Manjaro Linux x86_64
Kernel: 5.10.7-3-MANJARO
Uptime: 1 day, 1 hour, 4 mins
Packages: 1916 (pacman), 13 (flatpak)
Shell: zsh 5.8
Resolution: 1080x1920, 1920x1080
DE: i3-with-shmlog
WM: penrose
Theme: Adapta-Nokto-Eta-Maia [GTK2/3]
Icons: Papirus-Adapta-Nokto-Maia [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz
GPU: NVIDIA GeForce GTX 1080
Memory: 2716MiB / 32081MiB

current penrose develop

it works in both awesomewm and i3

**Comment by sminez** [comment]
Develop is as it sounds I'm afraid: if you are looking to use Penrose as your daily driver you should stick to the latest release on crates.io.

I have run steam previously under Penrose so I'm not sure why it wouldn't be working due to not having a systray...

If you can gather some more details about what is happening (debug logs are useful) then please do add them to the issue.


As a general rule, expect Penrose to   support fewer things than other window managers:

1. It is a library for you to write a window manager (not a full stand alone system out of the box)
2. It is a hobby project that was started less than a year ago and I am the sole developer (excluding a couple of user submitted patches) :wink:

**Comment by sminez** [comment]
Closing as this is related to `develop` at the time of raising and there has been no follow up
