### ISSUE TITLE
Widget with Text field updating via thread is only re-drawn when clients/focus/screens changes

### ISSUE THREAD

**Issue by jfchevrette** [sminez/penrose#136]
I'm very new to rust, so appologies for any bad code or misconceptions I may write below

### Describe the bug

I'm not sure this is a bug or a feature request but here goes. I've attempted to create my own Clock widget to display on the statusbar as provided by penrose. Since penrose does not seem to have concept of background timer or any mechanism to run widget code periodically I've implemented the Clock widget with a thread that sleeps every `refresh` duration seconds and updates the Text field using `Arc` and `Mutex`. My assuption was that when the Text is changed via `set_text`, the `require_draw` is set to `true` and that should get it updated on screen immediately. However it seems the bar is only redrawn on events such as client changes, focus changes, etc...

The Clock widget code is here: https://gist.github.com/jfchevrette/d8a9b7431c9e63480727cb919403aade

Looking through the available hooks, it doesn't seem there are any I should be using for this.

### Expected behavior

Expecting the widget to redraw because it's own `require_draw()` function returns the Text field's `require_draw()` which itself should be set to `true` after using `set_text()

### Versions & OS Details

- OS: linux
- Distribution: Arch
- Penrose Version: 34db716 (latest as of posting this)

**Comment by sminez** [comment]
Hi @jfchevrette 👋
I'm afraid that this is indeed a feature of how the status bar works: it is hook driven so the bar will re-render each time an event that it listens to is processed by the window manager. Penrose itself is single threaded so anything you want to try with background threads is going to need some additional plumbing in in order to work as program execution isn't going to be passed to the status bar otherwise.

A quick and dirty trick is to do something like setting the root window name, the bar listens for that and should refresh as a result 👍

Something more robust definitely _is_ possible but the bar itself would need to be able to grab a reference to the window manager on demand. I've been wondering about this already in the context of `pmenu` in the crates directory but that's a while off yet 😄
