### ISSUE TITLE
Direction: Left and Right

### ISSUE THREAD

**Issue by i-am-olep** [sminez/penrose#146]
I usually have 4 or more windows opened in the same workspace, so I would like to move Up, Down, Left and Right instead of cycling Forward/Backward

Maybe I'm missing something about the implementation of workspaces and opened windows, so is it a complex task? Or is just a matter of individual preferences that led to the absence of such possibility?

**Comment by sminez** [comment]
Workspaces store their client windows as an ordered stack (which is why cycling forward / backwards makes sense) but this gives no information about relative positions of nearby windows. It would be entirely possible to write something that worked out what left/right/up/down would mean but it will differ per layout (or require a "best effort" approach). Having layouts be simple, pure functions greatly simplifies their implementation which is something I'm definitely intending on keeping.

If you would like to try implementing such a helper function I'd be happy to include it in the contrib module, provided it was usable in the general case and not just for a particular layout :slightly_smiling:

**Comment by i-am-olep** [comment]
I don't know if I'm skilled enough for such a contribution, but I'll be happy to try. 

Thanks for your reply!

**Comment by sminez** [comment]
Finding a client that is in the right direction shouldn't be too hard, but making sure that it is the closest one might be fiddly to do in am efficient way. WMs like i3 handle this by storing windows in a tree, not an ring buffer, which supports this far better.

Penrose deliberately doesn't do that so that layout functions are free to position client's however you want (they can overlap, be positioned out of order etc) so you'll need to keep that in mind I'm afraid! :sweat_smile:
