### ISSUE TITLE
Fullscreen clients aren't fullscreen, when you switch to another workspace and back

### ISSUE THREAD

**Issue by legendofmiracles** [sminez/penrose#149]
### Describe the bug

When you make a client/window, then make it fullscreen, switch to another workspace and back, the app will be not anymore fullscreen, and to make it fullscreen again, you have to press your toggle button twice.

### To Reproduce

1. Open a window
2. toggle fullscreen on it
3. switch to another workspace, that isn't open currently
4. switch back
5. The window won't be in fullscreen anymore, to fix this you have to press your toggle button twice

### Expected behavior

It should stay in fullscreen, despite switching to another workspace. 

### Versions & OS Details

- OS: linux
- Distribution Arch
- OS Version latest
- Penrose Version 2.0

**Comment by sminez** [comment]
This will be down to the workspace switching logic not checking for full screen clients.

Full screen support in Penrose is _very_ minimal I'm afraid, so there are likely some other issues as well.

If you are interested in full screen support please do take a look at raising a PR for this :smile:

**Comment by legendofmiracles** [comment]
Sorry that i didn't respond earlier - Where should i look into adding this?

**Comment by sminez** [comment]
Hi @legendofmiracles , I've been having a look at what this would involve this morning and like I said, the fullscreen support is minimal at best. I was hoping it would be a case of just checking for fullscreen clients when mapping a workspace but the current code doesn't even enforce that there is only ever a single fullscreen client. I'm reasonably confident that the X server wouldn't allow that but the internal state looks like it could (and does) get messed up pretty easily...

I'll try to explain my thinking below but the tl;dr is "I'm going to need to overhaul how fullscreen works" so I'm afraid you'll need to leave this one with me. Doing it right is going to touch a lot of moving parts and I'll need to make sure I understand the implications and that there is good enough test coverage in place before that work can begin.

### The current set up

Full screen client support is incredibly bare bones: you can bind a key to toggle a client fullscreen and (hopefully) in app toggling to fullscreen should work as penrose accepts and processes client app requests to become fullscreen. Internally, this is tracked on he `Client` in question and the toggle between states results in mapping / unmapping other clients on the same workspace as the target.

This works provided (as you have seen) you don't change workspaces.

The fact that a client is currently fullscreen on a given workspace is not checked when switching to a new workspace so all windows are mapped / unmapped as if that were not the case. I originally thought that simply checking for a fullscreen client on workspace switch should be enough but it's not going to be that simple unfortunately.

### Why not so simple?

The current "solution" for fullscreen clients is defintely a hack: I wanted to be able to play Half Life 2 on Steam, that worked, I called it a day. It was never intended to be fully standards compliant, or robust in any sort of use case other than "I want this program fullscreen right now and I'll be closing it before doing anything else" (running a game or watching a video pretty much).

So, if we're going to do it properly there are a bunch of things to consider:
- What happens if the workspace for the fullscreen client gets moved to another screen?
- What happens if you try to move a fullscreen client to another workspace? (does that even make sense?)
- What if the output resolution changes for the given screen?
- What if the another client wants to become fullscreen?
- What happens if a fullscreen client dies / is killed?
- What happens if you change focus to another workspace and try to fullscreen a different client there?
- What do actions like `cycle_client` or `drag_client` do while something is fullscreen?
- ...

The quick and simple answer is "if something is fullscreen, workspace and client manipulation is disabled" but that sounds overly limiting and annoying (especially with multi-monitor). It would also mean that _everything_ would need to know and care about whether or not a client was currently fullscreen (including user written `hooks` which feels like a pretty bad API change).

So maybe something like popping the client _out_ of the workspace it is in and storing it on the screen makes sense, putting it back when it is no longer fullscreen. That has its own issues as you are able to dynamically add and remove workspaces so we'd also need to check that the workspace we're trying to move it to is still there. It also means that the current idea of "each screen holds a workspace" breaks as you'd then have "each screen holds a workspace _or_ a single fullscreen client".

That said, maybe this is the way to go? Moving a fullscreen client between screens would need to be handled carefully (along with the checks for when it is safe to remove a workspace) but that should be more isolated that requiring _everything_ to know about fullscreen clients.

### Next steps

I have some issues with dialog / transient clients to sort out first (see #129 and #120) but then I should be able to take a look at this and try to find a proper solution that doesn't have knock on effects for other actions.

A quick and dirty workaround in the meantime would be to write a hook for workspace change that did the "check if a client here is fullscreen and toggle it twice" trick. Sorry, I know that's gross but like I said: if this is going to be fixed it should be fixed properly, and adding that into the core of penrose directly _really_ should come with proper tests around the behaviour. My problem with that, is that I don't think it's the correct behaviour going forward.


Sorry for the rant! :sweat_smile: 

Hopefully this explains why I'm not going for the quick fix and calling it a day. Let me know if you need clarification on anything.

**Comment by legendofmiracles** [comment]
Thanks for the response, that's quite a handful!

This is not a pressing issue at all - so i really have nothing against this taking longer.
My usecase for this, is that when i play a game, i make it fullscreen. When i tab into another workspace, to e.g. respond to something on discord, and I tab back, the game isn't fullscreen. 
This is really only a minor inconvenience. Not a pressing issue, that *has* to be fixed *right now*. 

The hook will be more than enough in the meantime.

**Comment by sminez** [comment]
Closing as this was in relation to the previous API around full screen behaviour
