### ISSUE TITLE
Compilation error with examples/draw

### ISSUE THREAD

**Issue by cjwyett** [sminez/penrose#171]
### Describe the bug

Compilation error when using example config

### To Reproduce

1. Follow getting started guide until step 4
2. `wget https://raw.githubusercontent.com/sminez/penrose/develop/examples/draw/main.rs`
3. `mv main.rs src/main.rs`
4. `cargo build --release`

### Expected behavior

Compilation

### Screenshots

```
error[E0277]: the `?` operator can only be applied to values that implement `Try`
   --> src/main.rs:101:5
    |
101 |     drw.flush(id)?;
    |     ^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `()`
    |
    = help: the trait `Try` is not implemented for `()`
    = note: required by `into_result`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `my_penrose_config`

To learn more, run the command again with --verbose.

```
### Versions & OS Details

-  Arch BTW

**Comment by sminez** [comment]
"Follow getting started guide until step 4 and then do an unrelated thing results in a compilation error" is not an issue with the guide. Expected behaviour is _not_ "Compilation" as you state in your ticket.

If you are following the getting started example you are specifying a pinned version of `penrose` and then attempting to wget an example from the `develop` branch.

That is not going to work.

The guide gives you [an example](https://github.com/sminez/penrose/blob/develop/docs/getting_started.md#step-4-write-your-mainrs) to try. You are not only fetching a file from develop (which almost always won't work with a specified release version from crates.io), you are fetching a file that is a demo of the status bar rather than a `main.rs` for a window manager.

Running Arch has nothing to do with this: please follow the guide as it is written and it will work. I have just done this locally and it works fine (also on arch "btw").

**Comment by cjwyett** [comment]
Ah sorry, I got the impression that this would work from #167 .
