### ISSUE TITLE
Hiding windows that are internally managed

### ISSUE THREAD

**Issue by jooooscha** [sminez/penrose#175]
The only way that I managed to hide a client with `wm.hideclient(...)` was by marking the client as externally managed. 
Did I miss anything, or is this supposed to be like that?

**Comment by sminez** [comment]
Not explicitly no ...

Can you please take a look at the issue template for filing a bug and fill in the details it asks for? There's not much I can do without that. In particular, can you please provide a minimal reproduction of the issue

**Comment by jooooscha** [comment]
My bad. 

My use case is the following. I tried to implement a "swallowing" function similar to the dwm patch. The details are not important; however, I tried to call the function in a `new_client` hook. I confirmed, that the problem was not in my function by calling `hide_client` directly in the `new_client` hook. I also tried other hook functions without success.
The only way I found to hide a client was to mark that client as externally managed, which would require more manual managing.

# To reproduce: 

try calling `hide_client` in `new_client` hook.

# Problem

Does not hide the client. I tried with hiding the new client and with hiding the parent client (parent like the parent in the dwm patch)

**Comment by sminez** [comment]
Ok, so **new_client_hook**  triggers _before_  the client has been mapped. 

The main issue here is that your new client hook _is_ hiding the client (I suspect), but then the main logic for a new client spawning is remapping the client after your hook has run. You probably want / need to follow the logic used in the scratchpad  where a client is essentially tagged or tracked by **new_client_hook** and then that is picked up in the **event_handled** hook once the client has been mapped to the screen.

Everything works when you mark the client as externally managed because you are taking explicit control of the client in question and the main Penrose logic no longer attempts to map the client after your hook has run.

Hope that helps!

**Comment by jooooscha** [comment]
Thank you very much! This did help me a lot :)
