### ISSUE TITLE
Hidden windows still take up space

### ISSUE THREAD

**Issue by jooooscha** [sminez/penrose#176]
The use case is "swallowing" a terminal like in the dwm patch. To implement this I keep track of new windows in a `new_client` hook and hide them in the `event_handled` hook.

The issue is now that the windows are hidden, but still take up space. Think of it like setting a div in css to invisible instead of gone.

Do I have to call `hide_client` in another hook, or is this a bug?

Thanks for any help :)

**Comment by sminez** [comment]
Hmm...I'm going to guess that this is going to be because the client is being hidden from the screen but not correctly marked as not being visible in the workspace.

Same as last time, can you please use the issue template and provide the details asked for in there: debugging an issue with an end user written hook is pretty much impossible for me without a minimal example to go from...

**Comment by sminez** [comment]
Closing due to lack of follow up. If this is still something you still want to raise, please do so again using the issue template provided 🙂
