### ISSUE TITLE
Monitor independent workspaces

### ISSUE THREAD

**Issue by Kirottu** [sminez/penrose#178]
I ran into this "issue" where the focus would shift between monitors when focusing different workspaces, it feels really unnatural to me coming from a DWM background with each monitor having its own workspaces which are not shared between monitors in any way. I would like to see a feature to maybe toggle this behaviour.

**Comment by sminez** [comment]
Dwm uses a tag based system rather than workspaces so will see different behaviour when switching. The workspace behaviour in Penrose is very deliberate and one of the main reasons I wrote it rather than continuing to use dwm or qtile as mentioned in the README. If you want different workspace switching behaviour then you are able to implement that using the hooks system 🙂

Like it says in both the README and the FAQ: Penrose is a library not a binary. The intention is to act as a base layer that you use to write your own window manager.
