### ISSUE TITLE
`spawn` should make use of `AsRef<OsStr>`

### ISSUE THREAD

**Issue by F0Xde** [sminez/penrose#182]
`penrose::core::helpers::spawn` takes an argument with the trait bound `Into<String>`, which is only used as input for `std::process::Command` and could therefore be an `AsRef<OsStr>`. In order to do the whitespace splitting, the `as_bytes` method would have to be used, which could be split by `is_ascii_whitespace`.

I would be happy to contribute this minor change in case it is a desired improvement.

**Comment by F0Xde** [comment]
I quickly threw this together, not sure about the empty string though (the previous implementation `panic`ed on array access, while the `split` iterator always yields at least one item.

Additionally this would not treat non-ASCII whitespace as such, and while I don't believe this to be particularly important it would mean a clear change in behavior.

```rust
pub fn spawn<S: AsRef<OsStr>>(cmd: S) -> Result<()> {
    let mut args = cmd
        .as_ref()
        .as_bytes()
        .split(|b| b.is_ascii_whitespace())
        .map(|bytes| OsStr::from_bytes(bytes));

    // maybe we should check for an empty string beforehand?
    Command::new(args.next().expect("always one item in split"))
        .args(args)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()?;
    Ok(())
}
```

**Comment by sminez** [comment]
Hi @F0Xde, thanks for taking an interest in penrose.

Sorry if I'm being stupid here, but what problem does this solve? Changing the trait bound could potentially break existing use cases (unlikely but possible) and judging from [your PR](https://github.com/sminez/penrose/pull/183) you seem to be hitting some additional complications with using `OsStr`?

If this is just a "trait bound could be nicer so why not" thing then I'll close the issue and accompanying PR. But please do correct me if this is fixing an active issue for you!

**Comment by F0Xde** [comment]
You are right @sminez , it isn't necessary very often, but in few cases one may need to use non-UTF-8 data in a command. But I totally understand that it may not be worth the effort, especially if there's no nice way to do arg splitting.

Sorry for being ignorant, but what would be so bad about running `sh`? This seems to be what some other projects do, as it gives full shell behavior, including expansion of `~` and globbing.

**Comment by F0Xde** [comment]
The main question would be which shell to use; [sxhkd](https://github.com/baskerville/sxhkd/blob/fe241b0d2d70c9c483b23cf3cd14f1383f0953a2/src/sxhkd.c#L295) uses the `SHELL` or `SXHKD_SHELL` env var, while [i3](https://github.com/i3/i3/blob/fc65ca36b1f89f122b7ef0fe32c3bea1f46cfd27/src/startup.c#L195) makes use of `_BSHELL_PATH`

**Comment by sminez** [comment]
> in few cases one may need to use non-UTF-8 data in a command

Maybe? This helper is very definitely intended for running a command that is on your path, possibly with arguments. If you have non UTF-8 characters in that then I suspect you should probably look at using something else (like a wrapper script).

As for running `sh` from a rust `Command`, the whole point of Command is to safely call an external program. Calling `sh` first undermines that somewhat. Yes sxhkd and i3 run `sh` internally but they are also configured by static text files: this helper allows you to build up a string programmatically and pass that in. [Command](https://doc.rust-lang.org/std/process/struct.Command.html#method.args) makes sure that arguments are passed directly to the spawned program, _not_ via a shell so that the delightful world of shooting yourself in the foot with a malformed/malicious shell command is avoided.

I'm going to close this issue for now (along with the PR) as this doesn't seem to be in aid of fixing an active problem with the current implementation. If it does become an issue for you in future, please feel free to re-open the issue with details of why the change is needed 🙂
