### ISSUE TITLE
New tiling mode: Paper

### ISSUE THREAD

**Issue by petterssonjonas** [sminez/penrose#2]
Im impressed with what you have acomplished in such a short time!
I have a feature request that could make Penrose really stick out from the crowd, if you are interested, and able.
Check out the gnome addon PaperWM; it is a paper-tiler written in JS. I tried for a while, and it is awesome. My work flow felt so smooth. I just cant use gnome...
I dont believe any true tiling wm has this feature and it could make Penrose really stand out.
The original idea apparently came from here: http://10gui.com/

**Comment by sminez** [comment]
Looks interesting! I'll need to take a look at PaperWM in action to see how compatible it would be with the rest of Penrose, I suspect the full 10gui experience really only works with a large touch sensitive pad interface as shown in that video but you should be able to get pretty close... One thing this is highlighting for me though is that perhaps it would be good to pass through the full client objects themselves to the layout functions as then you'd have access to information like what the currently focused client was. Might make that change sooner rather than later so it can be built upon.
