### ISSUE TITLE
Be able to toggle fullscreen

### ISSUE THREAD

**Issue by ghost** [sminez/penrose#21]
---
name: Toggle Fullscreen and Client side Fullscreen
about: I want to be able to toggle fullscreen with a keybind like `M-f`. And for the client such as firefox to be able to fullscreen itself such as when user fullscreens a video on youtube.
title: Toggle Fullscreen and Client side Fullscreen
labels: enhancement

---

**Is your feature request related to a problem? Please describe.**
I would like to be able to fullscreen a client or at least put it in a monocle. And also for some reason when I fullscreen in firefox, it can't, and it also seems that the browser itself slows down when I try to fullscreen. I assume it is waiting for the window manager to fulfill the request, and it slows down as a result while waiting. I'm just guessing though.

**Describe the solution you'd like**
Have a public function that allows for toggling fullscreen, or at least have clients request to fullscreen.

**Comment by ghost** [comment]
Fixed the comment!

**Comment by sminez** [comment]
Hey @roelycooly , sorry about the delay in getting back to you: I'm working on implementing a simple status bar at the moment and my personal / works schedule is pretty hectic at the moment. In general, I've been following the example set by dwm where I can as it's a good minimal base to build from. Taking my personal fork as a reference point, I think it looks like these are the most important areas to focus on:

**dwm method**
https://github.com/sminez/suckless/blob/master/dwm/dwm.c#L671
https://github.com/sminez/suckless/blob/master/dwm/dwm.c#L719
https://github.com/sminez/suckless/blob/master/dwm/dwm.c#L1833

Theres also multiple operations and actions that are impacted by this (e.g. resizing, positioning, managing state etc) which are going to need to be handled I think. The way dwm partitions up the program state is different from penrose in a number of ways (partly to satisfy the borrow checker but also to support the sort of operations I'm after for penrose) so this won't be a direct translation.

I think the most important change is the fact that in order to do this, penrose will need to listen for and honour client messages which it currently doesn't do. I suspect this is why Firefox was freaking out on you? I'll need to find some time to look into it and work out how this breaks down: at the very least there needs to be some changes / additions to *XConn*, expanded event handling in *WindowManager* and possibly some more state management in *Client*. Im not sure exactly where the fullscreen state is best kept to be honest...there is currently an unused "fullscreen" flag on the Client struct but given that you can only really have one application fullscreen at a time, it might be better to handle everything from the WindowManager itself. I think there should probably also be a new hook for when a client gets made full screen as this is something that is going to affect anything that wants to have a say over rendering / screen layout.

**Comment by ghost** [comment]
@sminez Your personal life always comes first so I understand, so no need to apologize for the delay. Also yes your right, a week a back I was looking more into what could be causing the issue and it was just that penrose doesn't implement the _NET_WM_STATE_FULLSCREEN hint. I also looked into how dwm handles this hint, as it is my current wm, and from what I could tell when it receives this hint, it resizes the client window to the size of the screen with the XConfigureWindow function and raises the window. I do not know anything about about how to handle ewmh hints and all that jazz, but based from the dwm code I am guessing this is how it works. Now as for the hook, there probably should be a hook for XEvents in general for client messages, such as ewmh hints, as there is with the clientmessage function in dwm. (The procedure I mentioned for handling fullscreening was greatly paraphrased***)

**Comment by Danacus** [comment]
> Im not sure exactly where the fullscreen state is best kept to be honest...there is currently an unused "fullscreen" flag on the Client struct but given that you can only really have one application fullscreen at a time, it might be better to handle everything from the WindowManager itself.

Wouldn't it be possible for multiple Clients to be fullscreen? For example: a web browser playing a video on one workspace and a game running on another workspace. Perhaps it would make sense to store it in Workspace? Or you could maybe put it in WindowManager, but keep the fullscreen flag on Client to decide whether a Client should become the new fullscreen Client of WindowManager when switching to another Workspace.

**Comment by sminez** [comment]
@Danacus I _think_ multiple full screen clients should be fine but I need to look at how that is handled on the X server side. Listening to client requests for becoming full screen and tracking that state is actually the easier side of this: making sure that the correct thing is done with managing the X server messages and so on is a little more fiddly I suspect, particularly in relation to moving between workspaces when there is multi-monitor for example.

This issue isn't ready to be worked on yet: I need to have a look into what is required in terms of the X side of things as the `dwm` probably wont map directly to `penrose`. I've had a look at `awesome` and `qtile` as well but I want to make sure I get a good implementation.

**Comment by Danacus** [comment]
I don't have any experience with X server communication, so there's not much I can do. I'm just interested in this issue because it's probably the only thing keeping me from switching to penrose as a daily driver. But take your time, you don't have to hurry.
