### ISSUE TITLE
Replace functionality

### ISSUE THREAD

**Issue by MilesStorm** [sminez/penrose#217]
### Replace functionality akin to `xmonad --replace`

I am unable to find anything in the documentation or find a good solution to how to "replace", 
the current running window manager with a potential newly compiled version with changes.

### Change / addition I'd like to see made

It would be great if some sort of API was exposed to be able  to do this more easily,
it would allow for more rapid iteration on a configuration setup, 
or rapidly testing changes without having to log out and in of a session to reload the window manager.

### Alternatives I've considered
Currently the only way I can figure out how to do this on my own, or a way to simulate it at least, 
is to run penrose as a child X process on something like zephyr and replacing it through that.
This however is not quite optimal as I would like to daily drive penrose without having to run it as a child process.

**Comment by sminez** [comment]
Writing something to give you this functionality is definitely possible, but it probably wont be added to penrose itself given the "library rather than binary" nature of the project. For my own use I run the window manager like [this](https://github.com/sminez/my-penrose-config/blob/develop/bin/run-penrose) and handle restarting with a new build with a keybinding in a `dmenu` based prompt like [this](https://github.com/sminez/my-penrose-config/blob/develop/src/actions.rs#L23).

The aim of the project is primarily to be a stable daily driver once it is configured rather than something that you continually tinker with (my personal config has sat unchanged for over a year now I think) 🙂

As some added context, I _did_ look into hot reloading like this a while back but it introduced enough weird and wonderful edge cases to the rest of the system that I went back to the way things are now rather than complicate the design as a whole to support it.

**Comment by MilesStorm** [comment]
Thank you for taking the time to respond to my question.
Yeah I was a bit hesitant to ask the question in the first place, given that it would be more binary functionality that would make more sense for the individual user to create themselves.

But I very much appreciate the links you shared of your own config, can't believe I didn't think of something similar myself 😅
Incorporated an adaptation into my own configuration and it's working like a charm!

Very much appreciate what you've done with Penrose. I've been looking to replace Xmonad for some time, and Penrose exactly fit the bill of what I was looking for. Great work!
