### ISSUE TITLE
openBSD support 

### ISSUE THREAD

**Issue by icyrogue** [sminez/penrose#238]
Any chance it would be possible to compile it for openBSD and it's X display system instead of standard X11?

**Comment by sminez** [comment]
Not sure to be honest? The current implementation can be backed by either the x11rb crate or rust-xcb. If those work with BSD then you should be good to go, otherwise it'll require writing a new XConn impl :slightly_smiling:

I'm working on a rewrite of the main logic of this crate currently with the aim of being easier to test, reason about and extend. Part of that is trying to reduce the size of the XConn trait so if you don't mind holding off it might be worth the wait?

**Comment by icyrogue** [comment]
Sounds interesting, it isn't like openBSD is my daily driver, but I do use Penrose every day, so wanted to compile it for openBSD at least for the interest sake, I guess I got a chance of it working just like that. I don't feel like rewriting whole crate on my own tho, so I will be patiently waiting for your dependency update or how ever you call it.
