### ISSUE TITLE
Question: default widgets not refreshing

### ISSUE THREAD

**Issue by Katayounb** [sminez/penrose#264]
Hello,

The default built in widgets(date,  volume) doesn't seem to refresh by themselves, unless I change focus between windows or monitors. I'm using a simple config from the example section. 
Is it something that I am missing?

Thanks

**Comment by sminez** [comment]
Yeah most of the default widgets update when something else triggers a refreshing action rather than polling themselves (to avoid having spin loops lying around). The root window widget can be used in the same way as the standard dwm bar to be driven by an external script or program that sets the root window name every second for example. My personal config should have an example of how that works 👍

**Comment by greweln** [comment]
thank you!

**Comment by Katayounb** [comment]
thank you!
