### ISSUE TITLE
Ability to cycle to next/previous tag

### ISSUE THREAD

**Issue by griccardos** [sminez/penrose#280]
in `stack_set.rs` there is the ability to scroll to next/prev client and to next/prev screen.
Perhaps i missed it, but how does one cycle to next/prev tag? 

I know you can go to each tag directly, by calling it's name, but I think it would be useful to cycle also.

In main.rs one can currently do this:
```rust
        "M-j" => modify_with(|cs| cs.focus_down()),
        "M-k" => modify_with(|cs| cs.focus_up()),
        "M-bracketright" => modify_with(|cs| cs.next_screen()),
        "M-bracketleft" => modify_with(|cs| cs.previous_screen()),
```
proposed to also be able to do:
```rust
        "M-h" => modify_with(|cs| cs.previous_tag() ),
        "M-l" => modify_with(|cs| cs.next_tag() ),
```

I have already created a fix, let me know if you want  the PR.

**Comment by sminez** [comment]
So long as the cycling is implemented based on the workspace ID and handles invisible workspaces correctly (in that they should never be cycled to) that sounds like a worthwhile thing to add :+1:

**Comment by sminez** [comment]
Just had a look at the implementation you have on your fork here: https://github.com/sminez/penrose/commit/30b488e8f8951c1d001ccb27c78e5d7802f97276

While that looks like it should work, the repeated calls to `ordered_tags` will need tidying up so that we don't needlessly iterate multiple times through the window manager state. You also shouldn't need to be calling `update_previous_tag` I wouldn't of thought? It should just be a case of determining what the next/previous tag is and then the existing `focus_tag` method to handle updating all of the internal state.

**Comment by griccardos** [comment]
Great, thanks for the feedback! I will tidy up and update. 
you are correct about  `update_previous_tag` , I see it is called within `focus_tag` down the line so does not have to be called here again. Will remove.

**Comment by sminez** [comment]
@griccardos if this is still something you are interested in contributing I'm waiting on the quickcheck tests for the new methods, not sure if that was clear from the PR comments a few weeks ago?

Like I mentioned on the PR, I'm uneasy about providing this as methods on the `ClientSet` where they imply similar semantics and guarantees to the pure data structure based methods for things like cycling clients and screens. Penrose does not have a guaranteed internal ordering for workspaces (at least not one that is particularly useful in the general case for all users). I covered the design and behaviour of the pure data structures in one of the Penrose From Scratch episodes [here](https://www.youtube.com/watch?v=4r4CkXrPEbw&list=PLy2HjaQiG8lOxCKzuWKfmmXov4iEVOGOF&index=9). A key part of the design for Penrose is the declarative nature of operations on those data structures for manipulating internal state, which not really possible for cycling between tags.

I think what might be better is to have the functionality you have implemented as part of the [extensions::actions](https://github.com/sminez/penrose/blob/develop/src/extensions/actions/mod.rs) module? That way it is clear to users that the guarantees provided by the pure data structures do not apply here. That would also make it more palatable to return an error in some of the cases that you were wanting to set default values instead of using `expect` if that is the approach you would like to take?

**Comment by griccardos** [comment]
Hi @sminez not sure if you mean the tests i submitted to the PR? I did make the changes as requested, and they did pass.
Sure, if you think it best we can add it to `extensions::actions`. I'm not too familiar with that yet, so I can take a look and experiment a bit to see how it works, then can give you feedback.

**Comment by sminez** [comment]
No actually, I'm referring to the `quickcheck` property tests on the Stack methods that are used to implement the equivalent methods I'm talking about: https://github.com/sminez/penrose/blob/develop/src/pure/stack.rs#L915

The StackSet has its own quickcheck tests [here](https://github.com/sminez/penrose/blob/develop/src/pure/stack_set.rs#L1292) but they are targeting different things given that it's the behaviour of the underlying Stacks of Screens and Xids that provide the pure data structure invariants.

The purpose of these tests is to generate arbitrary inputs in order to do a form of directed fuzzing of the input space and get some confidence that there isn't any way for the function to misbehave around inputs that are atypical. The unit tests you have so far cover a couple of different cases for _one_ starting StackSet, which is much more a case of "is the happy path implementation correct".


Some relevant links:
https://en.wikipedia.org/wiki/QuickCheck
https://en.wikipedia.org/wiki/Software_testing#Property_testing
https://medium.com/criteo-engineering/introduction-to-property-based-testing-f5236229d237
