### ISSUE TITLE
Adding AltGr as a modifier

### ISSUE THREAD

**Issue by sysrqmagician** [sminez/penrose#293]
### Please describe the change / addition you'd like to see made

I'd like to be able to use the AltGr key (mod5 / ISO_Level3_Shift), featured on non-US keyboards in place of the right Alt key, as a modifier.
To this end, I somewhat over-zealously submitted PR #292 previously, which adds it to bindings.rs, including what I believe to be the correct mask: 0x80.

- Is this completely new functionality, or an enhancement to existing functionality?

An enhancement to existing functionality.

- What kind of feature is it that you are requesting?
  - [x] Changes to core
  - [ ] A new layout
  - [ ] A hook implementation
  - [ ] A custom extension
  - [ ] New X interactions
  - [ ] Other

### Is this a feature you have seen in other window managers?

No, I don't recall seeing it used as a mod key available by default like the common Super or Alt.

**Comment by sysrqmagician** [comment]
xev output showing mask 0x80 on state after pressing AltGr+a:
```
KeyPress event, serial 32, synthetic NO, window 0x5200001,
    root 0x1e6, subw 0x0, time 17414647, (893,643), root:(894,660),
    state 0x80, keycode 38 (keysym 0xe6, ae), same_screen YES,
    XLookupString gives 2 bytes: (c3 a6) "æ"
    XmbLookupString gives 2 bytes: (c3 a6) "æ"
    XFilterEvent returns: False
```
I wasn't sure where to look this up, but after finding that the bitshifts in the TryFrom impl for ModifierKey match the state value when pressing Ctrl and shift, I figured this would be it. It works on my machine with several different European layouts, at least (although I know that should not necessarily inspire confidence). 
If there's some sort of reference document for this, I'd appreciate if someone dropped a link.

**Comment by sminez** [comment]
Hi @sysrqmagician, I've been looking into this again and I keep finding references to `AltGr` being pretty annoying to use for keymappings due to the way it works, particularly the fact that there are multiple [dead](https://en.wikipedia.org/wiki/AltGr_key#X_Window_System) [keys](https://en.wikipedia.org/wiki/Dead_key) that it generates (which I _think_ vary based on the keyboard layout?).

https://chromestatus.com/feature/5059438092222464
https://www.reddit.com/r/i3wm/comments/709amk/how_to_set_mod_to_altgr/
https://unix.stackexchange.com/questions/240235/bind-alt-but-not-altgr-in-i3

I don't think I have the bandwidth to make sure that this behaves correctly for arbitrary keyboard layouts I'm afraid. Alternatives I've seen for other tiling window managers is to remap the physical `AltGr` key to another modifier and then use that in your keybindings.
