### ISSUE TITLE
Can't find display?

### ISSUE THREAD

**Issue by rootprt** [sminez/penrose#304]
### Describe the bug
I've gotten this type of bug before on other X11 managers, but never when executed through xinitrc.

When I run my xinit from a tty, i get a black screen with this error in the logs:

```

cat .penrose.log
2024-07-24T05:56:20.181856Z  INFO penrose::core: registering SIGCHILD signal handler
2024-07-24T05:56:20.181908Z  INFO manage_existing_clients: penrose::core: managing existing clients
2024-07-24T05:56:20.182049Z  INFO manage_existing_clients: penrose::core: unable to determine an active window: focusing first tag first_tag=1
2024-07-24T05:56:20.182058Z  INFO manage_existing_clients: penrose::core: triggering refresh

```

### Versions & OS Details

- OS: linux
- Arch
- Pulling version from git

### Additional context

Using the example config from the docs.

**Comment by sminez** [comment]
You'll need to share exactly what it is you are doing to start penrose rather than just the log for me to be able to say more I'm afraid. You're saying that you have an error in your log but what you've shared above is just info level logging of what I'd expect for normal startup?

**Comment by sminez** [comment]
Also, if you are running the example config from the docs (by which I assume you mean the [minimal](https://github.com/sminez/penrose/blob/develop/examples/minimal/main.rs) example?) then no background image is being set. Are you definitely getting an unresponsive blank screen rather than a desktop with no status bar? If you have `st` installed on your system then hitting `Mod+Enter` should spawn a terminal.

**Comment by sminez** [comment]
@prtcanfly I can see that you have a working config now so I'm assuming that this was working as intended rather than actually a bug. Please reopen if there is actually an issue here.
