### ISSUE TITLE
Example mouse bindings code out of date

### ISSUE THREAD

**Issue by codybloemhard** [sminez/penrose#305]
### Describe the bug

I tried out Penrose with the minimal example but it would not compile.
Specifically the code that handles the mouse bindings.
It cannot find `MouseDragHandler`, `MouseResizeHandler` and `click_handler`.
I tried importing them.

The type of the function seems to be wrong as well:

```
expected struct `std::collections::HashMap<(penrose::core::bindings::MouseEventKind, penrose::core::bindings::MouseState), _>`
               found struct `std::collections::HashMap<penrose::core::bindings::MouseState, _>`
```

I compile by just giving an empty hashmap as I don't need special mouse bindings.

### To Reproduce

Compile the minimal example on the latest version of Penrose.

### Expected behavior

Example is expected to compile.

### Versions & OS Details

- OS: Linux
- Distribution: Artix
- OS Version: 6.10.3-artix1-2
- Penrose Version: 0.3.5

**Comment by sminez** [comment]
You are compiling examples from the head of develop against the latest release on crates.io which isn't going to work. You can check out the tag for the 0.3.5 release to see the examples that are valid for use with it.

The mouse handlers you are talking about here are not part of 0.3.5 as I've not cut a new release since they were added I'm afraid.
