### ISSUE TITLE
Question: x11 vs x11rb in dependencies

### ISSUE THREAD

**Issue by nkruglikov** [sminez/penrose#315]
I see that the main `penrose` crate uses the `x11rb` Rust library, which is port of C xcb (newer X client library). The status bar `penrose_ui` crate, in the meantime, uses the `x11` Rust library, which is, as far as I understand, port of Xlib library (older, higher-level C library). My questions are:
- Why is that? What is the history here?
- Is there a plan to move `penrose_ui` to `x11rb`? Would that be hard?
- Does using Xlib in `penrose_ui` lead to performance problems? I am just a novice in X, but I heard that Xlib performs poorly because of its synchronous design.

**Comment by sminez** [comment]
It's down to the functionality needed: in penrose-ui I need access to xft fonts and as far as I'm aware, there isn't a great way to do that through x11rb. So no, there is no plan to try to move over to x11rb for penrose-ui 🙂

As for performance, xlib can be slower due to its synchronous API if you are writing a UI that has a lot of elements and interactions with the X server. penrose-ui however is about as simple as you can make a UI: it's block colour rectangles and polygons with static rendered text. For this use case there are no performance issues and the code is pretty simple to write and maintain.

Previously I used pango and cairo but that more than doubled the resulting binary size and build times for little to no benefit given the tiny amount of functionality penrose-ui exposes.

**Comment by nkruglikov** [comment]
Thank you for clarifications, and also for great project and prompt replies! :)
