### ISSUE TITLE
Floating windows shrink during repositioning

### ISSUE THREAD

**Issue by nkruglikov** [sminez/penrose#317]
Here's a screencast that shows the problem.

https://github.com/user-attachments/assets/fe07db95-ddba-485d-a5fc-12838bb02e43

Textual description: when a window is in floating mode, manipulating it with MouseDragHandler / MouseResizeHandler causes it to shrink on mouse button release. So, to reproduce:
- Make a window floating
- Drag it around
- On releasing drag, the window will shrink.

I've managed to track down the problem to this place: https://github.com/sminez/penrose/blob/f34bee141af02f3ee56a1414c761d58795d3fa56/src/x/mod.rs#L326-L341

Line 335 shrinks the client in order to account for its borders. This was added here: https://github.com/sminez/penrose/issues/246#issuecomment-1306759271

Indeed, if I comment out this line, the problems goes away (but tiled clients stop being positioned properly). 

I am still not entirely sure of the exact mechanism of the bug, because I wasn't able to understand why it happens only during mouse release, and not during mouse press and dragging.

The possible fix would be to add a check like this: `!screen_positions.contains(&r) && !<CLIENT IS FLOATING>` to line 334. I am open to trying to implement that.

**Comment by sminez** [comment]
I've fixed something similar recently for full screen clients: https://github.com/sminez/penrose/commit/a0f3669282bfb8a0eb926addc8187513fcfdab6d

The issue is exactly what you are describing so I suspect what is required is that the floating position is expanded to account for the border? I'm not 100% but I think that your fix of simply not shrinking the position will result in the border being drawn over the top of the client window rather than around it.

**Comment by nkruglikov** [comment]
Can you help me understand why this happens during mouse release but not during drag? It should coincide with calls to `modify_and_refresh`, but reading the code, I couldn't understand:
a) what is the path from handling the event to calling `modify_and_refresh` (in the event loop of WindowManager.run() there's just `x.flush()` )
b) why `modify_and_refresh` happens only on release.

(Re: similar fix: will look at it closer; just in case -- I am on develop branch, not on a stable version, because I saw this fix and thought it would remove my problem; it did not)

**Comment by sminez** [comment]
The fix I linked to is only for windows that are full screen so I wouldn't expect it to change anything here. As for why the shrinking only happens on release, I suspect that the answer is that the mouse handlers are directly calling `XConn::position_client` rather than `modify_and_refresh` which means they skip the resizing logic in `XConn::position_clients` (plural). On release I suspect there will be another event that is coming through and triggering the refresh which will result in the resize to what is then the consistent size. I think the actual fix is for the `position_client` calls in the mouse handler to shrink the current rectangle by the border size in the same way before positioning.

**Comment by sminez** [comment]
@nkruglikov this should be sorted now on `develop` following the above commit. I should hopefully have some time this week to get a new release out with the fix.
