### ISSUE TITLE
example of binding a key to a function that changes a config item

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#48]
**Is your feature request related to a problem? Please describe.**
I have a funuction

fn inc_dec_gap_size(config : &mut Config, offset : i32)  {
    if config.gap_px > 0 {
        config.gap_px = (config.gap_px as i32 + offset) as u32;
    }
}

that I would like to bind to a key like

        "M-plus" => inc_dec_gap_size(&mut config, 1),

**Describe the solution you'd like**
I would like an example that show how to do this as the above does not work

**Comment by sminez** [comment]
This isn't going to work I'm afraid: the `Config` struct is only used to initialise the `WindowManager` state. Mutations after the fact are not going to have any effect.
This should be possible if the relevant properties on the window manager are made public though. In which case your function would modify the relevant property on the `WindowManager` itself rather than your original `Config` struct.

**Comment by crypt17** [comment]
ok I will have a. look at the WindowManager. Is there a general layout that
is needed for a function called from a keybinding as couldn't get past the
compiler error stage.

**Comment by sminez** [comment]
Without the compiler error you are referring to there isn't much I can do.

There are multiple example configs show how to bind different actions to keys in the `examples` directory: you need to provide a Boxed function that is of type [FireAndForget](https://docs.rs/penrose/0.1.10/penrose/core/data_types/type.FireAndForget.html). The docs in https://docs.rs/penrose (or looking at the source) should show you how this works.

**Comment by crypt17** [comment]
ok I looked at FireAndForget but clearly didn't spend enough time with it.
Will have another look
