### ISSUE TITLE
Feature request: Dynamic workspace creation

### ISSUE THREAD

**Issue by TethysSvensson** [sminez/penrose#5]
I'm currently using xmonad with a combination of [`DynamicWorkspaces`][DynamicWorkspaces] and [`TopicSpace`][TopicSpace]. The first one allows for modifying the list of workspaces at runtime, while the second one means that I do not have to care about the order of the workspaces while I am using xmonad.

Would you be interested in supporting these use-cases at some point in the future? And would you accept PRs that works towards this goal?

[DynamicWorkspaces]: https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Actions-DynamicWorkspaces.html
[TopicSpace]: https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Actions-TopicSpace.html

**Comment by sminez** [comment]
Both sound interesting and definitely possible to add, though it will require some tweaks to the types currently being used in a few places I suspect. I'll need to read up on how the Xmonad implementations work first but I think in principle this should be doable without having to hook into the guts of **WindowManager** itself, though it will require some new public methods so that this can be set up from outside of the window manager.

Do you have any suggestions for an implementation? I'm definitely happy to accept PRs for this sort of thing provided the end result is an optional extension rather than something that is always required to be there 😄

**Comment by sminez** [comment]
I suppose with that in mind, it's probably also a good idea to isolate what the 'core' of Penrose is fairly soon, Vs the optional extensions.

**Comment by sminez** [comment]
Hi @TethysSvensson
The new hook support should hopefully allow you to have a crack at this if you are interested?

**Comment by sminez** [comment]
@TethysSvensson I know this isn't *quite* what you are after, but hopefully this shows you how to set up this sort of hook: https://github.com/sminez/penrose/blob/develop/src/contrib/hooks.rs#L54

**Comment by TethysSvensson** [comment]
@sminez Sorry for not replying. I'm still a bit busy, but I'm definitely planning on coming back to this to take another look.

**Comment by TethysSvensson** [comment]
As far as I can tell, there is still no possibility of creating workspaces on the fly or renaming existing ones?

**Comment by TethysSvensson** [comment]
Specifically workspaces still use a `&'static str`

**Comment by TethysSvensson** [comment]
As an example of why this is useful: I have a hotkey that creates a new workspace named `scratchpad-{n}` for some value of `n`. It then also creates a directory named `~/scratchpads/[current timestamp]` and spawns a terminal in that directory.

**Comment by sminez** [comment]
For adding/removing workspaces there are the [add_workspace](https://docs.rs/penrose/0.1.8/penrose/core/manager/struct.WindowManager.html#method.add_workspace) and [remove_workspace](https://docs.rs/penrose/0.1.8/penrose/core/manager/struct.WindowManager.html#method.remove_workspace) methods, along with [workspace](https://docs.rs/penrose/0.1.8/penrose/core/manager/struct.WindowManager.html#method.workspace) and [workspace_mut](https://docs.rs/penrose/0.1.8/penrose/core/manager/struct.WindowManager.html#method.workspace_mut) for getting references to existing workspaces. You can't currently modify the name of an [Workspace](https://docs.rs/penrose/0.1.8/penrose/core/workspace/struct.Workspace.html) (though adding that functionality is pretty simple).

The `&'static str` name can be made a String to allow for dynamic Workspace naming I suppose: the `&str`s that get passed to `config.workspaces` are only used to initialise the initial workspaces.

**Comment by sminez** [comment]
@TethysSvensson I've been [playing around](https://github.com/sminez/penrose/blob/develop/examples/dynamic_workspaces/main.rs) with the idea of dynamic workspace creation over the last few days. I've not ended up with exactly what you are after I don't think, rather a system that should allow for arbitrary dynamic workspaces to be defined through hooks and a couple of custom keybinding actions. I like to grab input using dmenu (see the script in the same directory) but that can be substituted for your program / method of choice for grabbing input.

For more traditional scratchpads I've written [this](https://github.com/sminez/penrose/blob/develop/src/contrib/extensions/scratchpad.rs) which is how I tend to make use of them. You could bind your "scratchpad running in a named directory" actions to trigger this if your terminal emulator allows for running some commands on startup (typically `-e` I think?)

**Comment by TethysSvensson** [comment]
@sminez If I understand your code correctly, then you are right; it's not exactly what I'm looking for. To support my use case, you would actually need the full flexibility of arbitrary renaming at runtime.

To be clear, I would not be offended at all if you just end up deciding that you do not want to support my use-case. I understand that it is somewhat specialized. Since I am also reasonably happy with my current xmonad setup, it would not be a great loss to me. However I am so much more comfortable coding or debugging rust than I am with haskell, that I was hoping that penrose could replace my current setup.

I've written at bit more below about my use-case below in case you are interested in hearing more about it. Otherwise feel free to close the issue. :wink:


### My setup

In my current setup, I have a list of pre-spawned workspaces with hooks for them, like in the examples. I a bit more than 10 different of these. I'm also using the traditional sort of scratchpad, i.e. a floating window that I can toggle with a keybinding. However neither of those are sufficient to support the way I am currently using xmonad.

For the sort of work I do, I often create very short-lived projects and/or run short code experiments. These things typically have a lifetime on the order of a few hours, and often deal with creating and/or downloading a few files that are self contained to that project. I do not necessarily know well in advance what projects will be working on, and I often work on a lot of project simultaneously.

I also want to keep some record of the stuff I've previously been working on, but I am fine with just grepping through the files to find what I am looking for.

The way I currently solve this is by creating new workspaces "on the fly". Initially these workspaces are just named `scratchpad-1`, `scratchpad-2`, etc. I have a hotkey to spawn a new workspace and it will just picks the lowest free name.

Whenever I spawn a terminal in these workspaces, the working directory is set to a directory created specifically for that workspace, e.g. `$HOME/scratchpads/2020-08-02-234343`. If I delete a workspace and this directory is still empty it will be deleted, otherwise I keep it for posterity in case I later need something from it.

If a project lives long enough (especially when I have many simultaneously), I start getting annoyed by referring to them as `scratchpad-7`, and I want a more recognizable name. For this I have a hotkey that e.g. lets me rename `scratchpad-7` to `super-awesome-project-of-the-day`.

This renaming matters a lot, since I never refer to a workspace by index, and always refer to it by name using fuzzy string search.

**Comment by sminez** [comment]
Ah ok, that makes a bit more sense now as to why the existing scratchpad implementation doesn't cover what you need! I _think_ you should be able to put this together with what is currently in penrose but you'll still need to use an external program like `dmenu` to do the rename / dynamic select without index.

The example I linked to previously allows for an arbitrary number of fixed workspaces and shows the mechanism for creating and adding a new workspace on the fly like you mention. For renaming, there is a `set_workspace_name` method that takes a `Selector` so you should be able to put something together to rename the focused workspace, workspace at index N, workspace matching a given condition (i.e. current name) etc. The same applies for `focus_workspace`: you pass a `Selector` so you should be able to put together a dmenu script that was populated by the current workspace list and then select from that. The rename and add/remove workspace functions all update `_NET_DESKTOP_NAMES` and `_NET_NUMBER_OF_DESKTOPS` when they are run so that external programs can find the current desktop/workspace set up.

Do you think that would be sufficient to implement what you are after?

**Comment by TethysSvensson** [comment]
Yep, I definitely think that would be enough! Thanks a lot for taking the effort to answer my questions!

I don't know when/if I have time to try porting my setup, but I'll let know you if I encounter any further problems on the way.
