### ISSUE TITLE
Suggestion: Allow the user to make the corners round and to add decoration to it.

### ISSUE THREAD

**Issue by Joe23232** [sminez/penrose#55]
I wanted to suggest a couple of features

* The ability to make the corners of the windows round (the roundness can be changed as well).
![image](https://user-images.githubusercontent.com/34926497/92297537-b71b5f00-ef83-11ea-9cac-0d9db176e925.png)

* To add decoration to the Windows (for example open, maximise, minimise etc.
![image](https://user-images.githubusercontent.com/34926497/92297510-77ed0e00-ef83-11ea-80e5-b6ec468850d4.png)

**Comment by sminez** [comment]
Neither of these features are likely to ever be included in the core of Penrose. You are able to write your own `XConn` implementation that does this if that is something you would like to implement.

If you are raising any further issues in this repo, please fill in the issue template rather than deleting it.

**Comment by Joe23232** [comment]
> You are able to write your own XConn implementation that does this if that is something you would like to implement.

Is this a low level implementation?

> If you are raising any further issues in this repo, please fill in the issue template rather than deleting it.

I am sorry but I don't think I deleted anything though?
