### ISSUE TITLE
applications should have penrose as a parent

### ISSUE THREAD

**Issue by crypt17** [sminez/penrose#58]
**Is your feature request related to a problem? Please describe.**
At present it appears that if yo attemmpt to restart penrose then all applications that have been spawned by penrose are killed

**Describe the solution you'd like**
I wold prefer that the parent is set to init as is done with many other window managers.

This would allow penrose to use an exit hook and dump its crrent state to disk that could then be read in by the replacement instance.

**Describe alternatives you've considered**
If there ase plants for another restart system that would better handle this I would be happy with that as well.

**Additional context**

**Comment by crypt17** [comment]
I may have been wrong about this. Would it be possible to have an exit hook so that saving of state can be triggered on exid in a standard way?

**Comment by Danacus** [comment]
> This would allow penrose to use an exit hook and dump its crrent state to disk that could then be read in by the replacement instance.

This is actually pretty complicated. I'm going to guess this is outside the scope of this project, but maybe it could be done with an extension?

> I may have been wrong about this. Would it be possible to have an exit hook so that saving of state can be triggered on exit in a standard way?

That would be possible with an extension that keeps track of all clients and saves the state to a file. It's the loading part that's more difficult, because as far as I know the only way to add clients to `WindowManager` is by actually starting new programs that create new windows. Maybe if `handle_map_request` would be public, or if a public `add_client` method that calls `handle_map_request` would be added?

**Comment by sminez** [comment]
It's less about having a way to add the client state in the WindowManager and more about the process / parent side of things. Penrose does not support recompile and restart in the way that something like xmonad does (which I think uses two processes to achieve this?) or hot config reloading due to the fact that you are writing a customer window manager program using Penrose as a library.

By all means as @danacus suggests, write an extension for Penrose if you can see a way or simply write your window manager program with this functionality. But Penrose is not designed with this use case in mind: rewriting and recompiling while using the window manager I mean. It is very deliberately minimal and something like this adds a lot of complexity to start up which is only needed if you are editing and recompiling your window manager which is not the general case.

**Comment by crypt17** [comment]
no issues. I have a few ideas on how I may be able to.do what I want
without any core.support.

One thing that I want to implement is to have something like the
perworkspace module from xmonad where a workspace could have different set
of layouts.from other workspaces. Is there any reason why this would eot be
possible if the workspace layouts were set up outside of init()

**Comment by sminez** [comment]
No that should be doable. The dynamic workspaces example should show you one way of doing that
