### ISSUE TITLE
Can't install penrose from crates.io

### ISSUE THREAD

**Issue by roland-5** [sminez/penrose#84]
Hi,

I tried download penrose with:
```
cargo install penrose
    Updating crates.io index
error: specified package `penrose v0.1.12` has no binaries
     Failed to install penrose (see error(s) above).
```

I use Arch linux, my rustup output:
```
rustup -V
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.50.0-nightly (f74583445 2020-12-18)`
```

Sorry for newbie question, but is there option to install it not as crate, but in system and choose in login manager?

**Comment by yohannd1** [comment]
Hello!

This error occurred because penrose doesn't have a binary that you can get directly from the crate - it's actually a library. To make a penrose binary, you should make your own crate, add penrose as a dependency, and then put on the main code file (by default `main.rs`) some code that actually uses penrose. See [this example](https://www.github.com/sminez/penrose/tree/develop/examples%2Fminimal%2Fmain.rs) to get a reference on what to put on `main.rs`.

After that, compile the program (on release mode, preferably) with `cargo build --release`. If everything goes well, you'll have the penrose binary on `<your project folder>/target/release/<your project name>`.

Finally, you can copy it to `/usr/bin` (be careful not to overwrite other files there!) with `sudo cp <binary name> -t /usr/bin`.

As for adding the window manager to your login screen, do you know which login manager you are using?

**Comment by roland-5** [comment]
@YohananDiamond Thank you so much! Everything goes well.
I use SDDM. I create /usr/share/xsessions/penrose.desktop

```
[Desktop Entry]
Version=1.0
Type=Application
Name=penrose
Comment=Lightweight X11 tiled window manager written in Rust
Exec=penrose
Icon=penrose
Terminal=false
StartupNotify=false
Categories=Application;
```

And I can choose penrose in SDDM and log in.
Thank you again!
