### ISSUE TITLE
Clients manually set to externally managed do not behave like clients automatically detected as externally managed

### ISSUE THREAD

**Issue by NeoDarkFire** [sminez/penrose#90]
### Describe the bug

I don't know if I should have created a pull request directly, so I'm writing a bug report just in case to discuss a thing I found in the code.
In the function `WindowManager::handle_map_request` (line 358 of `src/core/manager`):

When a client is automatically detected as externally managed, the window is just mapped and the function returns.

```Rust
        if !self.conn.is_managed_window(id) {
            debug!(
                "Handling map request for non-managed client: name[{}] id[{}] class[{}] type[{}]",
                name, id, class, ty
            );
            self.conn.map_window(id);
            return;
        }
```

However, if the client is set to externally managed by a hook, it executes the same code as managed windows without returning early:
```Rust
        run_hooks!(new_client, self, &mut client);
        let wix = client.workspace();

        if client.wm_managed {
            self.add_client_to_workspace(wix, id);
        }

        // The code continues !
```
This means that right now, the only difference between a managed client and a client that is set to externally managed inside a hook is the call to `add_client_to_workspace`.
As this is most likely not the expected behavior, I suggest adding an else branch as follow:
```Rust
        if client.wm_managed {
            self.add_client_to_workspace(wix, id);
        } else {
            self.conn.map_window(id);
            return;
        }
```

(Please let me know if this should have been a pull request right away)

**Comment by NeoDarkFire** [comment]
Although this fixes an issue I had with lemonbar, the suggestion above still needs some work, because that actually breaks the scratchpad :frowning_face: 
Unfortunately I won't be able to look more into it myself until I get back from work, but probably not focusing externally managed clients would be enough to resolve the issue I have with lemonbar

**Comment by sminez** [comment]
This is not a bug: you are mixing two concepts in `penrose` here:

**unmanaged clients**
```rust
const UNMANAGED_WINDOW_TYPES: &[Atom] = &[Atom::NetWindowTypeDock, Atom::NetWindowTypeToolbar];
```
Clients with a `_NET_WM_WINDOW_TYPE` in this set are completely ignored by `penrose` other than honouring the map request.

**externally managed clients**
```rust
if client.wm_managed {
    self.add_client_to_workspace(wix, id);
}
```
Clients marked with `wm_managed == false` by a hook are tracked by the `WindowManager` as a know client (for setting focus, removing etc) but are _not_ placed on a Workspace.


Your issue seems to be with how penrose identified **unmanaged clients** which I _think_ is down to the logic being written for the built in status bar, but that seems to be setting `_NET_WM_WINDOW_TYPE` as a utf8-string rather than an atom. This should be a simple fix so I'll raise an issue for that now. For comparison, this is the output for polybar:

```bash
$ xprop
_NET_WM_PID(CARDINAL) = 233148
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
WM_CLASS(STRING) = "polybar", "Polybar"
WM_NAME(STRING) = "penrose"
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 18, 0, 0, 0, 0, 0, 0, 1365, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 18, 0
```

And this is the output for the built in status bar:
```bash
$ xprop
_NET_WM_WINDOW_TYPE(UTF8_STRING) = "_NET_WM_WINDOW_TYPE_DOCK"
```


One last thing to try for other windows that have this problem: in my config I [mark polybar as floating](https://github.com/sminez/my-penrose-config/blob/develop/src/main.rs#L36) (along with some other programs) which is enough for it to behave as I would expect. Please do let me know if that is not behaving correctly either (though bare in mind that interaction with fullscreen windows is not something that is fully supported at the moment so there are likely some bugs there).
